### ISSUE TITLE
Update all files in a directory

### ISSUE THREAD

**Issue by svbackend** [loreanvictor/tmplr#1]
Cool project overall and I'm amazed by quality of documentation, just wanted to say huge thanks for your work!

**Comment by svbackend** [comment]
The only feature it's lacking is "update directories", for example I have template with bunch of java/kotlin files and in all of them I would like to replace "package com.example.projectname" by "package {{ tmplr.package }}" but looks like currently I need to specify all files manually or use some sort of bash command like `sed` which is not multiplatform and could not work on Windows

**Comment by loreanvictor** [comment]
Thanks! And thats a good use case. I am in the middle of restructuring the project into smaller packages, during that change will also add glob support to update command, which should do the trick, e.g.:

```yaml
update: src/**/*.java
```

**Comment by loreanvictor** [comment]
The [refactor](https://github.com/loreanvictor/tmplr/tree/tmplr-core-refactor) is [done](https://github.com/loreanvictor/tmplr/commit/547c8fae0848a1db4c2dd4e93a649156c6d12dc6), which means this feature is also on the latest version.
