### ISSUE TITLE
Support for local/private templates

### ISSUE THREAD

**Issue by ninomagazinovic** [loreanvictor/tmplr#11]
Hi,

Is it possible to create a project from local templates (`templates/*`)  that are not published in a seperate repository, but are part of a monorepo (pnpm workspace using NX package based approach).

Idea is to have a command like Vite `pnpm create vite my-vue-app --template vue` where the template can be either remote repository or local file path, it will create a folder with the provided name (can be exposed as default npm package name) and will copy content from local template or checkout (using degit) from remote repisitory.

Vite community templates are only supported using `degit` but without any project scaffolding as per documentation https://vitejs.dev/guide/#community-templates.

Im happy for `tmplr` and realy found it via the degit issue https://github.com/Rich-Harris/degit/issues/30, it is a good fit to scaffold a package based NX workspace and created seperate feature request https://github.com/nrwl/nx/issues/17979.

**Comment by loreanvictor** [comment]
I'm not sure if I understand exactly what you need, but:

- You can already get a template from a sub-directory of a published repository:
```bash
tmplr owner/repo/subdirectory
```
- You can use the [`run` command](https://github.com/loreanvictor/tmplr/tree/main#run) to run some local templating recipe:
```yml
# .tmplr.tml

run: ./templates/some-recipe.yml
```
Which can be combined with [`choices`](https://github.com/loreanvictor/tmplr/tree/main#choices) or [`prompt`](https://github.com/loreanvictor/tmplr/tree/main#prompt) to receive some parameters from the user and then fetch and run the desired template based on that input. You can even combine it with [`use`](https://github.com/loreanvictor/tmplr/tree/main#use) in case you want to run a remote repository, and you can check whether you need to run a local or a remote repository using the [`matches` pipe](https://github.com/loreanvictor/tmplr/tree/main#pipes).

What you currently can't do, but should be easy to add the support for:

- Allow running a local recipe other than `.tmplr.yml`, e.g. something like this:
```bash
tmplr -r ./templates/some-other-template.yml
```
- Allow accessing command line arguments inside a recipe, so you can read them and act accordingly. Basically the same syntax, but you'd need to handle it in the recipe yourself (might be a fun idea to implement generally, though it also might feel a bit too magical to users of `tmplr`, as the command line would start behaving differently based on locally present `.tmplr.yml` files).

**Comment by ninomagazinovic** [comment]
Yes, subdirectories are per degit support.

My thoughts were manly on private repositories and on the missing feature of Vite template to scaffold the project when we have to use custom templates (not the one provided by Vite)

For example Vite has out of the box templates https://vitejs.dev/guide/#scaffolding-your-first-vite-project that can be scaffoled like:
`pnpm create vite my-react-app --template react-ts`

where tmplr has to make it into three commands:
```
mkdir my-react-app
cd my-react-app
npx tmplr owner/repo
```

Idea was to have a single tmplr starter that can handle above in a single command like:
`pnpm create tmplr my-react-app --template owner/repo` (remote)
or for local template
`pnpm create tmplr my-react-app --template ./templates/react-app`

it will create directory my-react-app, cd into it, copy/checkout the project and run the tmplr recipe.

**Comment by loreanvictor** [comment]
Doing those 3 in one command line is already supported (though unfortunately, [not documented yet](https://github.com/loreanvictor/tmplr/issues/12)). You can do what you specified in one command like this:

```bash
npx tmplr owner/repo -d my-react-app
```

**Comment by ninomagazinovic** [comment]
Thanks a lot for the single command,

but you dont plan to support tmplr without the usage of degit?

**Comment by ninomagazinovic** [comment]
Thanks a lot for the solution.
Suggestion can be part of the documentation.

**Comment by loreanvictor** [comment]
further reflection on implementation: while allowing filesystems to also read from some out-of-scope addresses (predetermined on construction), and effectively separating read-scope from write-scope, this is a fundamental change with a lot of side effects, some perhaps involving security issues.

the leaner method would be to merely copy the contents of given folder into working directory, basically treating local files as another source. this can be done before any recipe is executed, removing the need to increase the execution scope of recipes in any way. additionally, this allows local templates to perfectly mirror remote templates, which should make it easier to write and maintain them.

this solution would perhaps look something like this:

```bash
npx tmplr file:./templates/first-template -d ./packages/my-new-package
```

**Comment by loreanvictor** [comment]
using local templates is supported from `0.2.13` onwards:
```bash
tmplr local:/my/template
```
